import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Footer from "@/components/Footer";
import Logo from "@/components/Logo";
import NavBar from "@/components/NavBar";
import HeaderSideContent from "@/components/HeaderSideContent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex flex-row h-20">
          <h1 className="sr-only">Your Brand</h1>
          <div className="Logo w-20 h-full flex items-center justify-center">
            <Logo></Logo>
          </div>
          <NavBar></NavBar>
          <HeaderSideContent></HeaderSideContent>
        </header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
